@builtinsemiring("GxB_MIN_FIRST")
@integerconstants("GxB_MIN_FIRST")
@unsignedintegerconstants("GxB_MIN_FIRST")
@floatconstants("GxB_MIN_FIRST")

@builtinsemiring("GxB_MAX_FIRST")
@integerconstants("GxB_MAX_FIRST")
@unsignedintegerconstants("GxB_MAX_FIRST")
@floatconstants("GxB_MAX_FIRST")

@builtinsemiring("GxB_PLUS_FIRST")
@integerconstants("GxB_PLUS_FIRST")
@unsignedintegerconstants("GxB_PLUS_FIRST")
@floatconstants("GxB_PLUS_FIRST")

@builtinsemiring("GxB_TIMES_FIRST")
@integerconstants("GxB_TIMES_FIRST")
@unsignedintegerconstants("GxB_TIMES_FIRST")
@floatconstants("GxB_TIMES_FIRST")

@builtinsemiring("GxB_ANY_FIRST")
@integerconstants("GxB_ANY_FIRST")
@unsignedintegerconstants("GxB_ANY_FIRST")
@floatconstants("GxB_ANY_FIRST")

@builtinsemiring("GxB_MIN_SECOND")
@integerconstants("GxB_MIN_SECOND")
@unsignedintegerconstants("GxB_MIN_SECOND")
@floatconstants("GxB_MIN_SECOND")

@builtinsemiring("GxB_MAX_SECOND")
@integerconstants("GxB_MAX_SECOND")
@unsignedintegerconstants("GxB_MAX_SECOND")
@floatconstants("GxB_MAX_SECOND")

@builtinsemiring("GxB_PLUS_SECOND")
@integerconstants("GxB_PLUS_SECOND")
@unsignedintegerconstants("GxB_PLUS_SECOND")
@floatconstants("GxB_PLUS_SECOND")

@builtinsemiring("GxB_TIMES_SECOND")
@integerconstants("GxB_TIMES_SECOND")
@unsignedintegerconstants("GxB_TIMES_SECOND")
@floatconstants("GxB_TIMES_SECOND")

@builtinsemiring("GxB_ANY_SECOND")
@integerconstants("GxB_ANY_SECOND")
@unsignedintegerconstants("GxB_ANY_SECOND")
@floatconstants("GxB_ANY_SECOND")

@builtinsemiring("GxB_MIN_PAIR")
@integerconstants("GxB_MIN_PAIR")
@unsignedintegerconstants("GxB_MIN_PAIR")
@floatconstants("GxB_MIN_PAIR")

@builtinsemiring("GxB_MAX_PAIR")
@integerconstants("GxB_MAX_PAIR")
@unsignedintegerconstants("GxB_MAX_PAIR")
@floatconstants("GxB_MAX_PAIR")

@builtinsemiring("GxB_PLUS_PAIR")
@integerconstants("GxB_PLUS_PAIR")
@unsignedintegerconstants("GxB_PLUS_PAIR")
@floatconstants("GxB_PLUS_PAIR")

@builtinsemiring("GxB_TIMES_PAIR")
@integerconstants("GxB_TIMES_PAIR")
@unsignedintegerconstants("GxB_TIMES_PAIR")
@floatconstants("GxB_TIMES_PAIR")

@builtinsemiring("GxB_ANY_PAIR")
@integerconstants("GxB_ANY_PAIR")
@unsignedintegerconstants("GxB_ANY_PAIR")
@floatconstants("GxB_ANY_PAIR")

@builtinsemiring("GxB_MIN_MIN")
@integerconstants("GxB_MIN_MIN")
@unsignedintegerconstants("GxB_MIN_MIN")
@floatconstants("GxB_MIN_MIN")

@builtinsemiring("GxB_MAX_MIN")
@integerconstants("GxB_MAX_MIN")
@unsignedintegerconstants("GxB_MAX_MIN")
@floatconstants("GxB_MAX_MIN")

@builtinsemiring("GxB_PLUS_MIN")
@integerconstants("GxB_PLUS_MIN")
@unsignedintegerconstants("GxB_PLUS_MIN")
@floatconstants("GxB_PLUS_MIN")

@builtinsemiring("GxB_TIMES_MIN")
@integerconstants("GxB_TIMES_MIN")
@unsignedintegerconstants("GxB_TIMES_MIN")
@floatconstants("GxB_TIMES_MIN")

@builtinsemiring("GxB_ANY_MIN")
@integerconstants("GxB_ANY_MIN")
@unsignedintegerconstants("GxB_ANY_MIN")
@floatconstants("GxB_ANY_MIN")

@builtinsemiring("GxB_MIN_MAX")
@integerconstants("GxB_MIN_MAX")
@unsignedintegerconstants("GxB_MIN_MAX")
@floatconstants("GxB_MIN_MAX")

@builtinsemiring("GxB_MAX_MAX")
@integerconstants("GxB_MAX_MAX")
@unsignedintegerconstants("GxB_MAX_MAX")
@floatconstants("GxB_MAX_MAX")

@builtinsemiring("GxB_PLUS_MAX")
@integerconstants("GxB_PLUS_MAX")
@unsignedintegerconstants("GxB_PLUS_MAX")
@floatconstants("GxB_PLUS_MAX")

@builtinsemiring("GxB_TIMES_MAX")
@integerconstants("GxB_TIMES_MAX")
@unsignedintegerconstants("GxB_TIMES_MAX")
@floatconstants("GxB_TIMES_MAX")

@builtinsemiring("GxB_ANY_MAX")
@integerconstants("GxB_ANY_MAX")
@unsignedintegerconstants("GxB_ANY_MAX")
@floatconstants("GxB_ANY_MAX")

@builtinsemiring("GxB_MIN_PLUS")
@integerconstants("GxB_MIN_PLUS")
@unsignedintegerconstants("GxB_MIN_PLUS")
@floatconstants("GxB_MIN_PLUS")

@builtinsemiring("GxB_MAX_PLUS")
@integerconstants("GxB_MAX_PLUS")
@unsignedintegerconstants("GxB_MAX_PLUS")
@floatconstants("GxB_MAX_PLUS")

@builtinsemiring("GxB_PLUS_PLUS")
@integerconstants("GxB_PLUS_PLUS")
@unsignedintegerconstants("GxB_PLUS_PLUS")
@floatconstants("GxB_PLUS_PLUS")

@builtinsemiring("GxB_TIMES_PLUS")
@integerconstants("GxB_TIMES_PLUS")
@unsignedintegerconstants("GxB_TIMES_PLUS")
@floatconstants("GxB_TIMES_PLUS")

@builtinsemiring("GxB_ANY_PLUS")
@integerconstants("GxB_ANY_PLUS")
@unsignedintegerconstants("GxB_ANY_PLUS")
@floatconstants("GxB_ANY_PLUS")

@builtinsemiring("GxB_MIN_MINUS")
@integerconstants("GxB_MIN_MINUS")
@unsignedintegerconstants("GxB_MIN_MINUS")
@floatconstants("GxB_MIN_MINUS")

@builtinsemiring("GxB_MAX_MINUS")
@integerconstants("GxB_MAX_MINUS")
@unsignedintegerconstants("GxB_MAX_MINUS")
@floatconstants("GxB_MAX_MINUS")

@builtinsemiring("GxB_PLUS_MINUS")
@integerconstants("GxB_PLUS_MINUS")
@unsignedintegerconstants("GxB_PLUS_MINUS")
@floatconstants("GxB_PLUS_MINUS")

@builtinsemiring("GxB_TIMES_MINUS")
@integerconstants("GxB_TIMES_MINUS")
@unsignedintegerconstants("GxB_TIMES_MINUS")
@floatconstants("GxB_TIMES_MINUS")

@builtinsemiring("GxB_ANY_MINUS")
@integerconstants("GxB_ANY_MINUS")
@unsignedintegerconstants("GxB_ANY_MINUS")
@floatconstants("GxB_ANY_MINUS")

@builtinsemiring("GxB_MIN_TIMES")
@integerconstants("GxB_MIN_TIMES")
@unsignedintegerconstants("GxB_MIN_TIMES")
@floatconstants("GxB_MIN_TIMES")

@builtinsemiring("GxB_MAX_TIMES")
@integerconstants("GxB_MAX_TIMES")
@unsignedintegerconstants("GxB_MAX_TIMES")
@floatconstants("GxB_MAX_TIMES")

@builtinsemiring("GxB_PLUS_TIMES")
@integerconstants("GxB_PLUS_TIMES")
@unsignedintegerconstants("GxB_PLUS_TIMES")
@floatconstants("GxB_PLUS_TIMES")

@builtinsemiring("GxB_TIMES_TIMES")
@integerconstants("GxB_TIMES_TIMES")
@unsignedintegerconstants("GxB_TIMES_TIMES")
@floatconstants("GxB_TIMES_TIMES")

@builtinsemiring("GxB_ANY_TIMES")
@integerconstants("GxB_ANY_TIMES")
@unsignedintegerconstants("GxB_ANY_TIMES")
@floatconstants("GxB_ANY_TIMES")

@builtinsemiring("GxB_MIN_DIV")
@integerconstants("GxB_MIN_DIV")
@unsignedintegerconstants("GxB_MIN_DIV")
@floatconstants("GxB_MIN_DIV")

@builtinsemiring("GxB_MAX_DIV")
@integerconstants("GxB_MAX_DIV")
@unsignedintegerconstants("GxB_MAX_DIV")
@floatconstants("GxB_MAX_DIV")

@builtinsemiring("GxB_PLUS_DIV")
@integerconstants("GxB_PLUS_DIV")
@unsignedintegerconstants("GxB_PLUS_DIV")
@floatconstants("GxB_PLUS_DIV")

@builtinsemiring("GxB_TIMES_DIV")
@integerconstants("GxB_TIMES_DIV")
@unsignedintegerconstants("GxB_TIMES_DIV")
@floatconstants("GxB_TIMES_DIV")

@builtinsemiring("GxB_ANY_DIV")
@integerconstants("GxB_ANY_DIV")
@unsignedintegerconstants("GxB_ANY_DIV")
@floatconstants("GxB_ANY_DIV")

@builtinsemiring("GxB_MIN_RDIV")
@integerconstants("GxB_MIN_RDIV")
@unsignedintegerconstants("GxB_MIN_RDIV")
@floatconstants("GxB_MIN_RDIV")

@builtinsemiring("GxB_MAX_RDIV")
@integerconstants("GxB_MAX_RDIV")
@unsignedintegerconstants("GxB_MAX_RDIV")
@floatconstants("GxB_MAX_RDIV")

@builtinsemiring("GxB_PLUS_RDIV")
@integerconstants("GxB_PLUS_RDIV")
@unsignedintegerconstants("GxB_PLUS_RDIV")
@floatconstants("GxB_PLUS_RDIV")

@builtinsemiring("GxB_TIMES_RDIV")
@integerconstants("GxB_TIMES_RDIV")
@unsignedintegerconstants("GxB_TIMES_RDIV")
@floatconstants("GxB_TIMES_RDIV")

@builtinsemiring("GxB_ANY_RDIV")
@integerconstants("GxB_ANY_RDIV")
@unsignedintegerconstants("GxB_ANY_RDIV")
@floatconstants("GxB_ANY_RDIV")

@builtinsemiring("GxB_MIN_RMINUS")
@integerconstants("GxB_MIN_RMINUS")
@unsignedintegerconstants("GxB_MIN_RMINUS")
@floatconstants("GxB_MIN_RMINUS")

@builtinsemiring("GxB_MAX_RMINUS")
@integerconstants("GxB_MAX_RMINUS")
@unsignedintegerconstants("GxB_MAX_RMINUS")
@floatconstants("GxB_MAX_RMINUS")

@builtinsemiring("GxB_PLUS_RMINUS")
@integerconstants("GxB_PLUS_RMINUS")
@unsignedintegerconstants("GxB_PLUS_RMINUS")
@floatconstants("GxB_PLUS_RMINUS")

@builtinsemiring("GxB_TIMES_RMINUS")
@integerconstants("GxB_TIMES_RMINUS")
@unsignedintegerconstants("GxB_TIMES_RMINUS")
@floatconstants("GxB_TIMES_RMINUS")

@builtinsemiring("GxB_ANY_RMINUS")
@integerconstants("GxB_ANY_RMINUS")
@unsignedintegerconstants("GxB_ANY_RMINUS")
@floatconstants("GxB_ANY_RMINUS")

@builtinsemiring("GxB_MIN_ISEQ")
@integerconstants("GxB_MIN_ISEQ")
@unsignedintegerconstants("GxB_MIN_ISEQ")
@floatconstants("GxB_MIN_ISEQ")

@builtinsemiring("GxB_MAX_ISEQ")
@integerconstants("GxB_MAX_ISEQ")
@unsignedintegerconstants("GxB_MAX_ISEQ")
@floatconstants("GxB_MAX_ISEQ")

@builtinsemiring("GxB_PLUS_ISEQ")
@integerconstants("GxB_PLUS_ISEQ")
@unsignedintegerconstants("GxB_PLUS_ISEQ")
@floatconstants("GxB_PLUS_ISEQ")

@builtinsemiring("GxB_TIMES_ISEQ")
@integerconstants("GxB_TIMES_ISEQ")
@unsignedintegerconstants("GxB_TIMES_ISEQ")
@floatconstants("GxB_TIMES_ISEQ")

@builtinsemiring("GxB_ANY_ISEQ")
@integerconstants("GxB_ANY_ISEQ")
@unsignedintegerconstants("GxB_ANY_ISEQ")
@floatconstants("GxB_ANY_ISEQ")

@builtinsemiring("GxB_MIN_ISNE")
@integerconstants("GxB_MIN_ISNE")
@unsignedintegerconstants("GxB_MIN_ISNE")
@floatconstants("GxB_MIN_ISNE")

@builtinsemiring("GxB_MAX_ISNE")
@integerconstants("GxB_MAX_ISNE")
@unsignedintegerconstants("GxB_MAX_ISNE")
@floatconstants("GxB_MAX_ISNE")

@builtinsemiring("GxB_PLUS_ISNE")
@integerconstants("GxB_PLUS_ISNE")
@unsignedintegerconstants("GxB_PLUS_ISNE")
@floatconstants("GxB_PLUS_ISNE")

@builtinsemiring("GxB_TIMES_ISNE")
@integerconstants("GxB_TIMES_ISNE")
@unsignedintegerconstants("GxB_TIMES_ISNE")
@floatconstants("GxB_TIMES_ISNE")

@builtinsemiring("GxB_ANY_ISNE")
@integerconstants("GxB_ANY_ISNE")
@unsignedintegerconstants("GxB_ANY_ISNE")
@floatconstants("GxB_ANY_ISNE")

@builtinsemiring("GxB_MIN_ISGT")
@integerconstants("GxB_MIN_ISGT")
@unsignedintegerconstants("GxB_MIN_ISGT")
@floatconstants("GxB_MIN_ISGT")

@builtinsemiring("GxB_MAX_ISGT")
@integerconstants("GxB_MAX_ISGT")
@unsignedintegerconstants("GxB_MAX_ISGT")
@floatconstants("GxB_MAX_ISGT")

@builtinsemiring("GxB_PLUS_ISGT")
@integerconstants("GxB_PLUS_ISGT")
@unsignedintegerconstants("GxB_PLUS_ISGT")
@floatconstants("GxB_PLUS_ISGT")

@builtinsemiring("GxB_TIMES_ISGT")
@integerconstants("GxB_TIMES_ISGT")
@unsignedintegerconstants("GxB_TIMES_ISGT")
@floatconstants("GxB_TIMES_ISGT")

@builtinsemiring("GxB_ANY_ISGT")
@integerconstants("GxB_ANY_ISGT")
@unsignedintegerconstants("GxB_ANY_ISGT")
@floatconstants("GxB_ANY_ISGT")

@builtinsemiring("GxB_MIN_ISLT")
@integerconstants("GxB_MIN_ISLT")
@unsignedintegerconstants("GxB_MIN_ISLT")
@floatconstants("GxB_MIN_ISLT")

@builtinsemiring("GxB_MAX_ISLT")
@integerconstants("GxB_MAX_ISLT")
@unsignedintegerconstants("GxB_MAX_ISLT")
@floatconstants("GxB_MAX_ISLT")

@builtinsemiring("GxB_PLUS_ISLT")
@integerconstants("GxB_PLUS_ISLT")
@unsignedintegerconstants("GxB_PLUS_ISLT")
@floatconstants("GxB_PLUS_ISLT")

@builtinsemiring("GxB_TIMES_ISLT")
@integerconstants("GxB_TIMES_ISLT")
@unsignedintegerconstants("GxB_TIMES_ISLT")
@floatconstants("GxB_TIMES_ISLT")

@builtinsemiring("GxB_ANY_ISLT")
@integerconstants("GxB_ANY_ISLT")
@unsignedintegerconstants("GxB_ANY_ISLT")
@floatconstants("GxB_ANY_ISLT")

@builtinsemiring("GxB_MIN_ISGE")
@integerconstants("GxB_MIN_ISGE")
@unsignedintegerconstants("GxB_MIN_ISGE")
@floatconstants("GxB_MIN_ISGE")

@builtinsemiring("GxB_MAX_ISGE")
@integerconstants("GxB_MAX_ISGE")
@unsignedintegerconstants("GxB_MAX_ISGE")
@floatconstants("GxB_MAX_ISGE")

@builtinsemiring("GxB_PLUS_ISGE")
@integerconstants("GxB_PLUS_ISGE")
@unsignedintegerconstants("GxB_PLUS_ISGE")
@floatconstants("GxB_PLUS_ISGE")

@builtinsemiring("GxB_TIMES_ISGE")
@integerconstants("GxB_TIMES_ISGE")
@unsignedintegerconstants("GxB_TIMES_ISGE")
@floatconstants("GxB_TIMES_ISGE")

@builtinsemiring("GxB_ANY_ISGE")
@integerconstants("GxB_ANY_ISGE")
@unsignedintegerconstants("GxB_ANY_ISGE")
@floatconstants("GxB_ANY_ISGE")

@builtinsemiring("GxB_MIN_ISLE")
@integerconstants("GxB_MIN_ISLE")
@unsignedintegerconstants("GxB_MIN_ISLE")
@floatconstants("GxB_MIN_ISLE")

@builtinsemiring("GxB_MAX_ISLE")
@integerconstants("GxB_MAX_ISLE")
@unsignedintegerconstants("GxB_MAX_ISLE")
@floatconstants("GxB_MAX_ISLE")

@builtinsemiring("GxB_PLUS_ISLE")
@integerconstants("GxB_PLUS_ISLE")
@unsignedintegerconstants("GxB_PLUS_ISLE")
@floatconstants("GxB_PLUS_ISLE")

@builtinsemiring("GxB_TIMES_ISLE")
@integerconstants("GxB_TIMES_ISLE")
@unsignedintegerconstants("GxB_TIMES_ISLE")
@floatconstants("GxB_TIMES_ISLE")

@builtinsemiring("GxB_ANY_ISLE")
@integerconstants("GxB_ANY_ISLE")
@unsignedintegerconstants("GxB_ANY_ISLE")
@floatconstants("GxB_ANY_ISLE")

@builtinsemiring("GxB_MIN_LOR")
@integerconstants("GxB_MIN_LOR")
@unsignedintegerconstants("GxB_MIN_LOR")
@floatconstants("GxB_MIN_LOR")

@builtinsemiring("GxB_MAX_LOR")
@integerconstants("GxB_MAX_LOR")
@unsignedintegerconstants("GxB_MAX_LOR")
@floatconstants("GxB_MAX_LOR")

@builtinsemiring("GxB_PLUS_LOR")
@integerconstants("GxB_PLUS_LOR")
@unsignedintegerconstants("GxB_PLUS_LOR")
@floatconstants("GxB_PLUS_LOR")

@builtinsemiring("GxB_TIMES_LOR")
@integerconstants("GxB_TIMES_LOR")
@unsignedintegerconstants("GxB_TIMES_LOR")
@floatconstants("GxB_TIMES_LOR")

@builtinsemiring("GxB_ANY_LOR")
@integerconstants("GxB_ANY_LOR")
@unsignedintegerconstants("GxB_ANY_LOR")
@floatconstants("GxB_ANY_LOR")

@builtinsemiring("GxB_MIN_LAND")
@integerconstants("GxB_MIN_LAND")
@unsignedintegerconstants("GxB_MIN_LAND")
@floatconstants("GxB_MIN_LAND")

@builtinsemiring("GxB_MAX_LAND")
@integerconstants("GxB_MAX_LAND")
@unsignedintegerconstants("GxB_MAX_LAND")
@floatconstants("GxB_MAX_LAND")

@builtinsemiring("GxB_PLUS_LAND")
@integerconstants("GxB_PLUS_LAND")
@unsignedintegerconstants("GxB_PLUS_LAND")
@floatconstants("GxB_PLUS_LAND")

@builtinsemiring("GxB_TIMES_LAND")
@integerconstants("GxB_TIMES_LAND")
@unsignedintegerconstants("GxB_TIMES_LAND")
@floatconstants("GxB_TIMES_LAND")

@builtinsemiring("GxB_ANY_LAND")
@integerconstants("GxB_ANY_LAND")
@unsignedintegerconstants("GxB_ANY_LAND")
@floatconstants("GxB_ANY_LAND")

@builtinsemiring("GxB_MIN_LXOR")
@integerconstants("GxB_MIN_LXOR")
@unsignedintegerconstants("GxB_MIN_LXOR")
@floatconstants("GxB_MIN_LXOR")

@builtinsemiring("GxB_MAX_LXOR")
@integerconstants("GxB_MAX_LXOR")
@unsignedintegerconstants("GxB_MAX_LXOR")
@floatconstants("GxB_MAX_LXOR")

@builtinsemiring("GxB_PLUS_LXOR")
@integerconstants("GxB_PLUS_LXOR")
@unsignedintegerconstants("GxB_PLUS_LXOR")
@floatconstants("GxB_PLUS_LXOR")

@builtinsemiring("GxB_TIMES_LXOR")
@integerconstants("GxB_TIMES_LXOR")
@unsignedintegerconstants("GxB_TIMES_LXOR")
@floatconstants("GxB_TIMES_LXOR")

@builtinsemiring("GxB_ANY_LXOR")
@integerconstants("GxB_ANY_LXOR")
@unsignedintegerconstants("GxB_ANY_LXOR")
@floatconstants("GxB_ANY_LXOR")

@builtinsemiring("GxB_LOR_NE")
@integerconstants("GxB_LOR_NE")
@unsignedintegerconstants("GxB_LOR_NE")
@floatconstants("GxB_LOR_NE")

@builtinsemiring("GxB_LOR_EQ")
@integerconstants("GxB_LOR_EQ")
@unsignedintegerconstants("GxB_LOR_EQ")
@floatconstants("GxB_LOR_EQ")

@builtinsemiring("GxB_LAND_EQ")
@integerconstants("GxB_LAND_EQ")
@unsignedintegerconstants("GxB_LAND_EQ")
@floatconstants("GxB_LAND_EQ")

@builtinsemiring("GxB_LXOR_EQ")
@integerconstants("GxB_LXOR_EQ")
@unsignedintegerconstants("GxB_LXOR_EQ")
@floatconstants("GxB_LXOR_EQ")

@builtinsemiring("GxB_EQ_EQ")
@integerconstants("GxB_EQ_EQ")
@unsignedintegerconstants("GxB_EQ_EQ")
@floatconstants("GxB_EQ_EQ")

@builtinsemiring("GxB_ANY_EQ")
@integerconstants("GxB_ANY_EQ")
@unsignedintegerconstants("GxB_ANY_EQ")
@floatconstants("GxB_ANY_EQ")

@builtinsemiring("GxB_LAND_NE")
@integerconstants("GxB_LAND_NE")
@unsignedintegerconstants("GxB_LAND_NE")
@floatconstants("GxB_LAND_NE")

@builtinsemiring("GxB_LXOR_NE")
@integerconstants("GxB_LXOR_NE")
@unsignedintegerconstants("GxB_LXOR_NE")
@floatconstants("GxB_LXOR_NE")

@builtinsemiring("GxB_EQ_NE")
@integerconstants("GxB_EQ_NE")
@unsignedintegerconstants("GxB_EQ_NE")
@floatconstants("GxB_EQ_NE")

@builtinsemiring("GxB_ANY_NE")
@integerconstants("GxB_ANY_NE")
@unsignedintegerconstants("GxB_ANY_NE")
@floatconstants("GxB_ANY_NE")

@builtinsemiring("GxB_LOR_GT")
@integerconstants("GxB_LOR_GT")
@unsignedintegerconstants("GxB_LOR_GT")
@floatconstants("GxB_LOR_GT")

@builtinsemiring("GxB_LAND_GT")
@integerconstants("GxB_LAND_GT")
@unsignedintegerconstants("GxB_LAND_GT")
@floatconstants("GxB_LAND_GT")

@builtinsemiring("GxB_LXOR_GT")
@integerconstants("GxB_LXOR_GT")
@unsignedintegerconstants("GxB_LXOR_GT")
@floatconstants("GxB_LXOR_GT")

@builtinsemiring("GxB_EQ_GT")
@integerconstants("GxB_EQ_GT")
@unsignedintegerconstants("GxB_EQ_GT")
@floatconstants("GxB_EQ_GT")

@builtinsemiring("GxB_ANY_GT")
@integerconstants("GxB_ANY_GT")
@unsignedintegerconstants("GxB_ANY_GT")
@floatconstants("GxB_ANY_GT")

@builtinsemiring("GxB_LOR_LT")
@integerconstants("GxB_LOR_LT")
@unsignedintegerconstants("GxB_LOR_LT")
@floatconstants("GxB_LOR_LT")

@builtinsemiring("GxB_LAND_LT")
@integerconstants("GxB_LAND_LT")
@unsignedintegerconstants("GxB_LAND_LT")
@floatconstants("GxB_LAND_LT")

@builtinsemiring("GxB_LXOR_LT")
@integerconstants("GxB_LXOR_LT")
@unsignedintegerconstants("GxB_LXOR_LT")
@floatconstants("GxB_LXOR_LT")

@builtinsemiring("GxB_EQ_LT")
@integerconstants("GxB_EQ_LT")
@unsignedintegerconstants("GxB_EQ_LT")
@floatconstants("GxB_EQ_LT")

@builtinsemiring("GxB_ANY_LT")
@integerconstants("GxB_ANY_LT")
@unsignedintegerconstants("GxB_ANY_LT")
@floatconstants("GxB_ANY_LT")

@builtinsemiring("GxB_LOR_GE")
@integerconstants("GxB_LOR_GE")
@unsignedintegerconstants("GxB_LOR_GE")
@floatconstants("GxB_LOR_GE")

@builtinsemiring("GxB_LAND_GE")
@integerconstants("GxB_LAND_GE")
@unsignedintegerconstants("GxB_LAND_GE")
@floatconstants("GxB_LAND_GE")

@builtinsemiring("GxB_LXOR_GE")
@integerconstants("GxB_LXOR_GE")
@unsignedintegerconstants("GxB_LXOR_GE")
@floatconstants("GxB_LXOR_GE")

@builtinsemiring("GxB_EQ_GE")
@integerconstants("GxB_EQ_GE")
@unsignedintegerconstants("GxB_EQ_GE")
@floatconstants("GxB_EQ_GE")

@builtinsemiring("GxB_ANY_GE")
@integerconstants("GxB_ANY_GE")
@unsignedintegerconstants("GxB_ANY_GE")
@floatconstants("GxB_ANY_GE")

@builtinsemiring("GxB_LOR_LE")
@integerconstants("GxB_LOR_LE")
@unsignedintegerconstants("GxB_LOR_LE")
@floatconstants("GxB_LOR_LE")

@builtinsemiring("GxB_LAND_LE")
@integerconstants("GxB_LAND_LE")
@unsignedintegerconstants("GxB_LAND_LE")
@floatconstants("GxB_LAND_LE")

@builtinsemiring("GxB_LXOR_LE")
@integerconstants("GxB_LXOR_LE")
@unsignedintegerconstants("GxB_LXOR_LE")
@floatconstants("GxB_LXOR_LE")

@builtinsemiring("GxB_EQ_LE")
@integerconstants("GxB_EQ_LE")
@unsignedintegerconstants("GxB_EQ_LE")
@floatconstants("GxB_EQ_LE")

@builtinsemiring("GxB_ANY_LE")
@integerconstants("GxB_ANY_LE")
@unsignedintegerconstants("GxB_ANY_LE")
@floatconstants("GxB_ANY_LE")

@builtinsemiring("GxB_LOR_FIRST")
@booleanconstant("GxB_LOR_FIRST")
@builtinsemiring("GxB_LAND_FIRST")
@booleanconstant("GxB_LAND_FIRST")
@builtinsemiring("GxB_LXOR_FIRST")
@booleanconstant("GxB_LXOR_FIRST")
@builtinsemiring("GxB_EQ_FIRST")
@booleanconstant("GxB_EQ_FIRST")
@builtinsemiring("GxB_ANY_FIRST")
@booleanconstant("GxB_ANY_FIRST")
@builtinsemiring("GxB_LOR_SECOND")
@booleanconstant("GxB_LOR_SECOND")
@builtinsemiring("GxB_LAND_SECOND")
@booleanconstant("GxB_LAND_SECOND")
@builtinsemiring("GxB_LXOR_SECOND")
@booleanconstant("GxB_LXOR_SECOND")
@builtinsemiring("GxB_EQ_SECOND")
@booleanconstant("GxB_EQ_SECOND")
@builtinsemiring("GxB_ANY_SECOND")
@booleanconstant("GxB_ANY_SECOND")
@builtinsemiring("GxB_LOR_PAIR")
@booleanconstant("GxB_LOR_PAIR")
@builtinsemiring("GxB_LAND_PAIR")
@booleanconstant("GxB_LAND_PAIR")
@builtinsemiring("GxB_LXOR_PAIR")
@booleanconstant("GxB_LXOR_PAIR")
@builtinsemiring("GxB_EQ_PAIR")
@booleanconstant("GxB_EQ_PAIR")
@builtinsemiring("GxB_ANY_PAIR")
@booleanconstant("GxB_ANY_PAIR")
@builtinsemiring("GxB_LOR_LOR")
@booleanconstant("GxB_LOR_LOR")
@builtinsemiring("GxB_LAND_LOR")
@booleanconstant("GxB_LAND_LOR")
@builtinsemiring("GxB_LXOR_LOR")
@booleanconstant("GxB_LXOR_LOR")
@builtinsemiring("GxB_EQ_LOR")
@booleanconstant("GxB_EQ_LOR")
@builtinsemiring("GxB_ANY_LOR")
@booleanconstant("GxB_ANY_LOR")
@builtinsemiring("GxB_LOR_LAND")
@booleanconstant("GxB_LOR_LAND")
@builtinsemiring("GxB_LAND_LAND")
@booleanconstant("GxB_LAND_LAND")
@builtinsemiring("GxB_LXOR_LAND")
@booleanconstant("GxB_LXOR_LAND")
@builtinsemiring("GxB_EQ_LAND")
@booleanconstant("GxB_EQ_LAND")
@builtinsemiring("GxB_ANY_LAND")
@booleanconstant("GxB_ANY_LAND")
@builtinsemiring("GxB_LOR_LXOR")
@booleanconstant("GxB_LOR_LXOR")
@builtinsemiring("GxB_LAND_LXOR")
@booleanconstant("GxB_LAND_LXOR")
@builtinsemiring("GxB_LXOR_LXOR")
@booleanconstant("GxB_LXOR_LXOR")
@builtinsemiring("GxB_EQ_LXOR")
@booleanconstant("GxB_EQ_LXOR")
@builtinsemiring("GxB_ANY_LXOR")
@booleanconstant("GxB_ANY_LXOR")
@builtinsemiring("GxB_LOR_EQ")
@booleanconstant("GxB_LOR_EQ")
@builtinsemiring("GxB_LAND_EQ")
@booleanconstant("GxB_LAND_EQ")
@builtinsemiring("GxB_LXOR_EQ")
@booleanconstant("GxB_LXOR_EQ")
@builtinsemiring("GxB_EQ_EQ")
@booleanconstant("GxB_EQ_EQ")
@builtinsemiring("GxB_ANY_EQ")
@booleanconstant("GxB_ANY_EQ")
@builtinsemiring("GxB_LOR_GT")
@booleanconstant("GxB_LOR_GT")
@builtinsemiring("GxB_LAND_GT")
@booleanconstant("GxB_LAND_GT")
@builtinsemiring("GxB_LXOR_GT")
@booleanconstant("GxB_LXOR_GT")
@builtinsemiring("GxB_EQ_GT")
@booleanconstant("GxB_EQ_GT")
@builtinsemiring("GxB_ANY_GT")
@booleanconstant("GxB_ANY_GT")
@builtinsemiring("GxB_LOR_LT")
@booleanconstant("GxB_LOR_LT")
@builtinsemiring("GxB_LAND_LT")
@booleanconstant("GxB_LAND_LT")
@builtinsemiring("GxB_LXOR_LT")
@booleanconstant("GxB_LXOR_LT")
@builtinsemiring("GxB_EQ_LT")
@booleanconstant("GxB_EQ_LT")
@builtinsemiring("GxB_ANY_LT")
@booleanconstant("GxB_ANY_LT")
@builtinsemiring("GxB_LOR_GE")
@booleanconstant("GxB_LOR_GE")
@builtinsemiring("GxB_LAND_GE")
@booleanconstant("GxB_LAND_GE")
@builtinsemiring("GxB_LXOR_GE")
@booleanconstant("GxB_LXOR_GE")
@builtinsemiring("GxB_EQ_GE")
@booleanconstant("GxB_EQ_GE")
@builtinsemiring("GxB_ANY_GE")
@booleanconstant("GxB_ANY_GE")
@builtinsemiring("GxB_LOR_LE")
@booleanconstant("GxB_LOR_LE")
@builtinsemiring("GxB_LAND_LE")
@booleanconstant("GxB_LAND_LE")
@builtinsemiring("GxB_LXOR_LE")
@booleanconstant("GxB_LXOR_LE")
@builtinsemiring("GxB_EQ_LE")
@booleanconstant("GxB_EQ_LE")
@builtinsemiring("GxB_ANY_LE")
@booleanconstant("GxB_ANY_LE")

@builtinsemiring("GxB_PLUS_FIRST")
@complexconstants("GxB_PLUS_FIRST")
@builtinsemiring("GxB_TIMES_FIRST")
@complexconstants("GxB_TIMES_FIRST")
@builtinsemiring("GxB_ANY_FIRST")
@complexconstants("GxB_ANY_FIRST")
@builtinsemiring("GxB_PLUS_SECOND")
@complexconstants("GxB_PLUS_SECOND")
@builtinsemiring("GxB_TIMES_SECOND")
@complexconstants("GxB_TIMES_SECOND")
@builtinsemiring("GxB_ANY_SECOND")
@complexconstants("GxB_ANY_SECOND")
@builtinsemiring("GxB_PLUS_PAIR")
@complexconstants("GxB_PLUS_PAIR")
@builtinsemiring("GxB_TIMES_PAIR")
@complexconstants("GxB_TIMES_PAIR")
@builtinsemiring("GxB_ANY_PAIR")
@complexconstants("GxB_ANY_PAIR")
@builtinsemiring("GxB_PLUS_PLUS")
@complexconstants("GxB_PLUS_PLUS")
@builtinsemiring("GxB_TIMES_PLUS")
@complexconstants("GxB_TIMES_PLUS")
@builtinsemiring("GxB_ANY_PLUS")
@complexconstants("GxB_ANY_PLUS")
@builtinsemiring("GxB_PLUS_MINUS")
@complexconstants("GxB_PLUS_MINUS")
@builtinsemiring("GxB_TIMES_MINUS")
@complexconstants("GxB_TIMES_MINUS")
@builtinsemiring("GxB_ANY_MINUS")
@complexconstants("GxB_ANY_MINUS")
@builtinsemiring("GxB_PLUS_TIMES")
@complexconstants("GxB_PLUS_TIMES")
@builtinsemiring("GxB_TIMES_TIMES")
@complexconstants("GxB_TIMES_TIMES")
@builtinsemiring("GxB_ANY_TIMES")
@complexconstants("GxB_ANY_TIMES")
@builtinsemiring("GxB_PLUS_DIV")
@complexconstants("GxB_PLUS_DIV")
@builtinsemiring("GxB_TIMES_DIV")
@complexconstants("GxB_TIMES_DIV")
@builtinsemiring("GxB_ANY_DIV")
@complexconstants("GxB_ANY_DIV")
@builtinsemiring("GxB_PLUS_RDIV")
@complexconstants("GxB_PLUS_RDIV")
@builtinsemiring("GxB_TIMES_RDIV")
@complexconstants("GxB_TIMES_RDIV")
@builtinsemiring("GxB_ANY_RDIV")
@complexconstants("GxB_ANY_RDIV")
@builtinsemiring("GxB_PLUS_RMINUS")
@complexconstants("GxB_PLUS_RMINUS")
@builtinsemiring("GxB_TIMES_RMINUS")
@complexconstants("GxB_TIMES_RMINUS")
@builtinsemiring("GxB_ANY_RMINUS")
@complexconstants("GxB_ANY_RMINUS")

@builtinsemiring("GxB_BOR_BOR")
@unsignedintegerconstants("GxB_BOR_BOR")
@builtinsemiring("GxB_BOR_BAND")
@unsignedintegerconstants("GxB_BOR_BAND")
@builtinsemiring("GxB_BOR_BXOR")
@unsignedintegerconstants("GxB_BOR_BXOR")
@builtinsemiring("GxB_BOR_BXNOR")
@unsignedintegerconstants("GxB_BOR_BXNOR")
@builtinsemiring("GxB_BAND_BOR")
@unsignedintegerconstants("GxB_BAND_BOR")
@builtinsemiring("GxB_BAND_BAND")
@unsignedintegerconstants("GxB_BAND_BAND")
@builtinsemiring("GxB_BAND_BXOR")
@unsignedintegerconstants("GxB_BAND_BXOR")
@builtinsemiring("GxB_BAND_BXNOR")
@unsignedintegerconstants("GxB_BAND_BXNOR")
@builtinsemiring("GxB_BXOR_BOR")
@unsignedintegerconstants("GxB_BXOR_BOR")
@builtinsemiring("GxB_BXOR_BAND")
@unsignedintegerconstants("GxB_BXOR_BAND")
@builtinsemiring("GxB_BXOR_BXOR")
@unsignedintegerconstants("GxB_BXOR_BXOR")
@builtinsemiring("GxB_BXOR_BXNOR")
@unsignedintegerconstants("GxB_BXOR_BXNOR")
@builtinsemiring("GxB_BXNOR_BOR")
@unsignedintegerconstants("GxB_BXNOR_BOR")
@builtinsemiring("GxB_BXNOR_BAND")
@unsignedintegerconstants("GxB_BXNOR_BAND")
@builtinsemiring("GxB_BXNOR_BXOR")
@unsignedintegerconstants("GxB_BXNOR_BXOR")
@builtinsemiring("GxB_BXNOR_BXNOR")
@unsignedintegerconstants("GxB_BXNOR_BXNOR")

@builtinsemiring("GxB_MIN_FIRSTI")
@positionalconstants("GxB_MIN_FIRSTI")
@builtinsemiring("GxB_MAX_FIRSTI")
@positionalconstants("GxB_MAX_FIRSTI")
@builtinsemiring("GxB_ANY_FIRSTI")
@positionalconstants("GxB_ANY_FIRSTI")
@builtinsemiring("GxB_PLUS_FIRSTI")
@positionalconstants("GxB_PLUS_FIRSTI")
@builtinsemiring("GxB_TIMES_FIRSTI")
@positionalconstants("GxB_TIMES_FIRSTI")
@builtinsemiring("GxB_MIN_FIRSTI1")
@positionalconstants("GxB_MIN_FIRSTI1")
@builtinsemiring("GxB_MAX_FIRSTI1")
@positionalconstants("GxB_MAX_FIRSTI1")
@builtinsemiring("GxB_ANY_FIRSTI1")
@positionalconstants("GxB_ANY_FIRSTI1")
@builtinsemiring("GxB_PLUS_FIRSTI1")
@positionalconstants("GxB_PLUS_FIRSTI1")
@builtinsemiring("GxB_TIMES_FIRSTI1")
@positionalconstants("GxB_TIMES_FIRSTI1")
@builtinsemiring("GxB_MIN_FIRSTJ")
@positionalconstants("GxB_MIN_FIRSTJ")
@builtinsemiring("GxB_MAX_FIRSTJ")
@positionalconstants("GxB_MAX_FIRSTJ")
@builtinsemiring("GxB_ANY_FIRSTJ")
@positionalconstants("GxB_ANY_FIRSTJ")
@builtinsemiring("GxB_PLUS_FIRSTJ")
@positionalconstants("GxB_PLUS_FIRSTJ")
@builtinsemiring("GxB_TIMES_FIRSTJ")
@positionalconstants("GxB_TIMES_FIRSTJ")
@builtinsemiring("GxB_MIN_FIRSTJ1")
@positionalconstants("GxB_MIN_FIRSTJ1")
@builtinsemiring("GxB_MAX_FIRSTJ1")
@positionalconstants("GxB_MAX_FIRSTJ1")
@builtinsemiring("GxB_ANY_FIRSTJ1")
@positionalconstants("GxB_ANY_FIRSTJ1")
@builtinsemiring("GxB_PLUS_FIRSTJ1")
@positionalconstants("GxB_PLUS_FIRSTJ1")
@builtinsemiring("GxB_TIMES_FIRSTJ1")
@positionalconstants("GxB_TIMES_FIRSTJ1")
@builtinsemiring("GxB_MIN_SECONDI")
@positionalconstants("GxB_MIN_SECONDI")
@builtinsemiring("GxB_MAX_SECONDI")
@positionalconstants("GxB_MAX_SECONDI")
@builtinsemiring("GxB_ANY_SECONDI")
@positionalconstants("GxB_ANY_SECONDI")
@builtinsemiring("GxB_PLUS_SECONDI")
@positionalconstants("GxB_PLUS_SECONDI")
@builtinsemiring("GxB_TIMES_SECONDI")
@positionalconstants("GxB_TIMES_SECONDI")
@builtinsemiring("GxB_MIN_SECONDI1")
@positionalconstants("GxB_MIN_SECONDI1")
@builtinsemiring("GxB_MAX_SECONDI1")
@positionalconstants("GxB_MAX_SECONDI1")
@builtinsemiring("GxB_ANY_SECONDI1")
@positionalconstants("GxB_ANY_SECONDI1")
@builtinsemiring("GxB_PLUS_SECONDI1")
@positionalconstants("GxB_PLUS_SECONDI1")
@builtinsemiring("GxB_TIMES_SECONDI1")
@positionalconstants("GxB_TIMES_SECONDI1")
@builtinsemiring("GxB_MIN_SECONDJ")
@positionalconstants("GxB_MIN_SECONDJ")
@builtinsemiring("GxB_MAX_SECONDJ")
@positionalconstants("GxB_MAX_SECONDJ")
@builtinsemiring("GxB_ANY_SECONDJ")
@positionalconstants("GxB_ANY_SECONDJ")
@builtinsemiring("GxB_PLUS_SECONDJ")
@positionalconstants("GxB_PLUS_SECONDJ")
@builtinsemiring("GxB_TIMES_SECONDJ")
@positionalconstants("GxB_TIMES_SECONDJ")
@builtinsemiring("GxB_MIN_SECONDJ1")
@positionalconstants("GxB_MIN_SECONDJ1")
@builtinsemiring("GxB_MAX_SECONDJ1")
@positionalconstants("GxB_MAX_SECONDJ1")
@builtinsemiring("GxB_ANY_SECONDJ1")
@positionalconstants("GxB_ANY_SECONDJ1")
@builtinsemiring("GxB_PLUS_SECONDJ1")
@positionalconstants("GxB_PLUS_SECONDJ1")
@builtinsemiring("GxB_TIMES_SECONDJ1")
@positionalconstants("GxB_TIMES_SECONDJ1")

@builtinsemiring("GrB_PLUS_TIMES_SEMIRING")
@integerconstants("GrB_PLUS_TIMES_SEMIRING")
@unsignedintegerconstants("GrB_PLUS_TIMES_SEMIRING")
@floatconstants("GrB_PLUS_TIMES_SEMIRING")

@builtinsemiring("GrB_PLUS_MIN_SEMIRING")
@integerconstants("GrB_PLUS_MIN_SEMIRING")
@unsignedintegerconstants("GrB_PLUS_MIN_SEMIRING")
@floatconstants("GrB_PLUS_MIN_SEMIRING")

@builtinsemiring("GrB_MIN_PLUS_SEMIRING")
@integerconstants("GrB_MIN_PLUS_SEMIRING")
@unsignedintegerconstants("GrB_MIN_PLUS_SEMIRING")
@floatconstants("GrB_MIN_PLUS_SEMIRING")

@builtinsemiring("GrB_MIN_TIMES_SEMIRING")
@integerconstants("GrB_MIN_TIMES_SEMIRING")
@unsignedintegerconstants("GrB_MIN_TIMES_SEMIRING")
@floatconstants("GrB_MIN_TIMES_SEMIRING")

@builtinsemiring("GrB_MIN_FIRST_SEMIRING")
@integerconstants("GrB_MIN_FIRST_SEMIRING")
@unsignedintegerconstants("GrB_MIN_FIRST_SEMIRING")
@floatconstants("GrB_MIN_FIRST_SEMIRING")

@builtinsemiring("GrB_MIN_SECOND_SEMIRING")
@integerconstants("GrB_MIN_SECOND_SEMIRING")
@unsignedintegerconstants("GrB_MIN_SECOND_SEMIRING")
@floatconstants("GrB_MIN_SECOND_SEMIRING")

@builtinsemiring("GrB_MIN_MAX_SEMIRING")
@integerconstants("GrB_MIN_MAX_SEMIRING")
@unsignedintegerconstants("GrB_MIN_MAX_SEMIRING")
@floatconstants("GrB_MIN_MAX_SEMIRING")

@builtinsemiring("GrB_MAX_PLUS_SEMIRING")
@integerconstants("GrB_MAX_PLUS_SEMIRING")
@unsignedintegerconstants("GrB_MAX_PLUS_SEMIRING")
@floatconstants("GrB_MAX_PLUS_SEMIRING")

@builtinsemiring("GrB_MAX_TIMES_SEMIRING")
@integerconstants("GrB_MAX_TIMES_SEMIRING")
@unsignedintegerconstants("GrB_MAX_TIMES_SEMIRING")
@floatconstants("GrB_MAX_TIMES_SEMIRING")

@builtinsemiring("GrB_MAX_FIRST_SEMIRING")
@integerconstants("GrB_MAX_FIRST_SEMIRING")
@unsignedintegerconstants("GrB_MAX_FIRST_SEMIRING")
@floatconstants("GrB_MAX_FIRST_SEMIRING")

@builtinsemiring("GrB_MAX_SECOND_SEMIRING")
@integerconstants("GrB_MAX_SECOND_SEMIRING")
@unsignedintegerconstants("GrB_MAX_SECOND_SEMIRING")
@floatconstants("GrB_MAX_SECOND_SEMIRING")

@builtinsemiring("GrB_MAX_MIN_SEMIRING")
@integerconstants("GrB_MAX_MIN_SEMIRING")
@unsignedintegerconstants("GrB_MAX_MIN_SEMIRING")
@floatconstants("GrB_MAX_MIN_SEMIRING")

@builtinsemiring("GrB_LOR_LAND_SEMIRING")
@booleanconstant("GrB_LOR_LAND_SEMIRING")
@builtinsemiring("GrB_LAND_LOR_SEMIRING")
@booleanconstant("GrB_LAND_LOR_SEMIRING")
@builtinsemiring("GrB_LXOR_LAND_SEMIRING")
@booleanconstant("GrB_LXOR_LAND_SEMIRING")
@builtinsemiring("GrB_LXNOR_LOR_SEMIRING")
@booleanconstant("GrB_LXNOR_LOR_SEMIRING")