include("modulemacro.jl")
unaryglobalnames = [:GrB_IDENTITY_BOOL, :GrB_AINV_BOOL, :GrB_MINV_BOOL, :GxB_LNOT_BOOL, :GrB_IDENTITY_INT8, :GrB_AINV_INT8, :GrB_MINV_INT8, :GxB_LNOT_INT8, :GrB_IDENTITY_INT16, :GrB_AINV_INT16, :GrB_MINV_INT16, :GxB_LNOT_INT16, :GrB_IDENTITY_INT32, :GrB_AINV_INT32, :GrB_MINV_INT32, :GxB_LNOT_INT32, :GrB_IDENTITY_INT64, :GrB_AINV_INT64, :GrB_MINV_INT64, :GxB_LNOT_INT64, :GrB_IDENTITY_UINT8, :GrB_AINV_UINT8, :GrB_MINV_UINT8, :GxB_LNOT_UINT8, :GrB_IDENTITY_UINT16, :GrB_AINV_UINT16, :GrB_MINV_UINT16, :GxB_LNOT_UINT16, :GrB_IDENTITY_UINT32, :GrB_AINV_UINT32, :GrB_MINV_UINT32, :GxB_LNOT_UINT32, :GrB_IDENTITY_UINT64, :GrB_AINV_UINT64, :GrB_MINV_UINT64, :GxB_LNOT_UINT64, :GrB_IDENTITY_FP32, :GrB_AINV_FP32, :GrB_MINV_FP32, :GxB_LNOT_FP32, :GrB_IDENTITY_FP64, :GrB_AINV_FP64, :GrB_MINV_FP64, :GxB_LNOT_FP64, :GxB_ONE_BOOL, :GrB_ABS_BOOL, :GxB_ONE_INT8, :GrB_ABS_INT8, :GrB_BNOT_INT8, :GxB_ONE_INT16, :GrB_ABS_INT16, :GrB_BNOT_INT16, :GxB_ONE_INT32, :GrB_ABS_INT32, :GrB_BNOT_INT32, :GxB_ONE_INT64, :GrB_ABS_INT64, :GrB_BNOT_INT64, :GxB_ONE_UINT8, :GrB_ABS_UINT8, :GrB_BNOT_UINT8, :GxB_ONE_UINT16, :GrB_ABS_UINT16, :GrB_BNOT_UINT16, :GxB_ONE_UINT32, :GrB_ABS_UINT32, :GrB_BNOT_UINT32, :GxB_ONE_UINT64, :GrB_ABS_UINT64, :GrB_BNOT_UINT64, :GxB_ONE_FP32, :GrB_ABS_FP32, :GxB_ONE_FP64, :GrB_ABS_FP64, :GxB_ONE_FC32, :GxB_ONE_FC64, :GrB_LNOT]

function loadglobalunaryops()
    for uname ∈ unaryglobalnames
        x = "_" * String(uname)
        x = Symbol(x)
        eval(:(@createunaryopstruct $x))
    end

end
